### ISSUE TITLE
available dataset

### ISSUE THREAD

**Issue by gyillikci** [rameau-fr/CCTV-Calib#3]
Hi,

Thanks for the work. is there a dataset to use?

Best,

Giray

**Comment by rameau-fr** [comment]
Dear Giray,

Thank you very much for your interest in our work. What dataset would you like to use?

Regarding the calibration dataset, the test set on Google Studio images can be found via the following [link](https://drive.google.com/file/d/1UDSzvUZyJTKXhu2SNraA1EPsxQUy9-K_/view?usp=sharing)
If you can wait until next week, I might be able to provide you with some "in the wild" sequences captured online but without any ground truth. They are essentially just videos to validate your approach.

However, if you are seeking the dataset to train the 3D vehicle detection, I am not sharing it as it is originally the DISCO dataset that I modified in many ways to normalize the 3D keypoints coordinates and where we applied some style transfer to improve the robustness to domain shifts. Interestingly, I am now unable to find back the DISCO dataset that was shared by NEC Lab. The paper where they were providing this dataset was entitled: "Deep Supervision with Intermediate Concepts". If this is what you need, I hope you will be able to find it somewhere online.
Alternatively, I have recently seen another paper proposing a similar type of dataset [here](https://skope3d.github.io/) but I have not tried it yet.

I hope it helps!

**Comment by gyillikci** [comment]
Hello Francois,

Thanks for your reply. I am not looking for the 3D Car dataset. I actually would like to use it for building interior. I am planning to match view points of cameras with the blueprint of the building floor for humans. I just wanted the dataset to jump start with known data (thanks for sharing) 
ıt would be very kind if you can share the "in the wild" sequences. My main goal is to understand the tool as much as possible.
again thanks for your work.

Best

PS: I will not close the issue since you would share "in the wild" dataset through here. But don't hesitate to close it. I ll eventually close it.

**Comment by rameau-fr** [comment]
Thank you so much for testing this toolbox; I understand exactly what you are trying to do. Actually, I have also used this toolbox precisely for the same use case you are describing. Unfortunately, due to the limited number of keypoints available in the blueprints and the relative inaccuracy of these points (depending on the accuracy and resolution of the blueprint you are using), the results were not always very reliable, and I had to do quite a lot of modifications and tricks.

Indeed, let's keep this issue open until I share additional data; it could be helpful for anyone.
Also, if you encounter any problems, I would be glad if you could report them so that I can correct them when I have time.

Best,

**Comment by rameau-fr** [comment]
As promised, here is the dataset in the wild I was mentioning about: [link to download](https://drive.google.com/file/d/18KznclsEu_DI1GZ7cfKYhJlmZdF_1LQq/view?usp=sharing)
I will now close this issue, but please feel free to open any new request if you are testing the toolbox!

Thank you very much for your interest!

**Comment by gyillikci** [comment]
thank you Francois,

Best
